// USO DEL SELECT:

SELECT name
from users;

SELECT * 
FROM USERS;

SELECT user_id
from users;

// SELECCIONAMOS LAS COLUMNAS (SELECT NAME, SELECT *, SELECT USER_ID) Y USAMOS EL FROM PARA
SELECCIONAR LA TABLA, EN ESTE CASO SERIA LA TABLA USERS //

OBS: Si ponemos SELECT  y un asterisco (*), seleccionaremos todas las filas y COLUMNAS
de la tabla.

OBS2: Los punto y comas al final de cada codigo finalizado, se usa para separar las 
sentencias 