SELECT DISTINCT NAME 
FROM users;

	SELECT DISTINCT age
	From Users;

    // EL DISTINCT SE USA PARA MOSTRAR LOS NOMBRES DIFERENTES DE CADA PERSONA, O EDAD,
    O LO QUE SE LE PIDA EN EL SELECT DISTINCT, ASI EVITAMOS QUE NOS MUESTRE LOS VALORES
    REPETIDOS //
    